export const MODAL_ACTION_TYPES = {
  SET_WELCOME_SIGN_IN: "modal/SET_WELCOME_SIGN_IN",
  SET_PRO_SIGN_IN: "modal/SET_PRO_SIGN_IN",
  SET_SAVE_THREADS_SIGN_IN: "modal/SET_SAVE_THREADS_SIGN_IN",
  SET_TRY_PRO_SEARCH_SIGN_IN: "modal/SET_TRY_PRO_SEARCH_SIGN_IN",
  SET_ATTACHMENT_SIGN_IN: "modal/SET_ATTACHMENT_SIGN_IN",
  SET_INITIAL_SIGN_IN: "modal/SET_INITIAL_SIGN_IN",
  SET_ADD_THREAD: "modal/SET_ADD_THREAD",
}